services:
  alexa2anylist:
    build: .
    image: alexiri/alexa2anylist:latest
    volumes:
      - /data/alexa2anylist:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Madrid
    restart: unless-stopped
